# base iamge to build npm relted only (stage 1)


FROM node:18 AS builder


WORKDIR /app


COPY package*.json ./


RUN npm install


COPY . .


## base iamge to build RUN Application only (small image)


FROM node:18-alpine 


WORKDIR /app

COPY --from=builder /app .

EXPOSE 5173

CMD ["npm", "run",  "dev"]



